name: Publish VS Code Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install
      
    - name: Install vsce
      run: npm install -g @vscode/vsce
      
    - name: Package extension
      run: |
        vsce package
        ls -la *.vsix
        
    - name: Upload extension artifact
      uses: actions/upload-artifact@v4
      with:
        name: extension-package-${{ github.ref_name }}
        path: "*.vsix"
        retention-days: 90
        
    - name: Publish to VS Code Marketplace
      run: vsce publish
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}