name: Publish VS Code Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install
      
    - name: Install vsce
      run: npm install -g @vscode/vsce
      
    - name: Package extension
      run: |
        vsce package
        ls -la *.vsix
        
    - name: Upload extension artifact
      uses: actions/upload-artifact@v4
      with:
        name: extension-package-${{ github.ref_name }}
        path: "*.vsix"
        retention-days: 90
        
    - name: Publish to VS Code Marketplace
      run: vsce publish
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
        
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          ## Changes in this release
          
          This release includes the following themes:
          - Solarized Light VS
          - Tomorrow Night VS
          
          ## Installation
          
          You can install this extension from the [VS Code Marketplace](https://marketplace.visualstudio.com/items?itemName=xivilay.simplified-themes-mods-pack) or search for "Simplified Themes Mods Pack" in VS Code.
          
          ## Manual Installation
          
          Download the `.vsix` file from the assets below and install it manually:
          1. Open VS Code
          2. Go to Extensions (Ctrl+Shift+X)
          3. Click the "..." menu and select "Install from VSIX..."
          4. Select the downloaded `.vsix` file
        draft: false
        prerelease: false
        files: "*.vsix"
